from colorama import Fore
def main():
    print(Fore.GREEN+"""
    |* * * * * * * * * * OOOOOOOOOOOOOOOOOOOOOOOOO|
    | * * * * * * * * *  OOOOOOOOOOOOOOOOOOOOOOOOO|
    |* * * * * * * * * * OOOOOOOOOOOOOOOOOOOOOOOOO|
    | * * * * * * * * *  OOOOOOOOOOOOOOOOOOOOOOOOO|
    |* * * * * * * * * * OOOOOOOOOOOOOOOOOOOOOOOOO|
    | * * * * * * * * *  OOOOOOOOOOOOOOOOOOOOOOOOO|
    |* * * * * * * * * * OOOOOOOOOOOOOOOOOOOOOOOOO|
    |OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|
    |OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|
    |OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|
    |OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|
    |OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|
    |OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO| """)
    print(Fore.BLUE+"IN GOD WE TRUST")
    print(Fore.RED+"E Pluribus Unum")
